name: Build and Deploy
on:
  pull_request:
    types: [opened, synchronize]
    
jobs:
  run-test-cases:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check current version of node
        run: node -v

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules_cache_{{ checksum "package-lock.json" }}

      - name: Run test cases
        run: npm run coverage

      - name: Store artifact
        uses: actions/upload-artifact@v3
        with:
          name: discussion
          path: coverage

      - name: install sonar scanner
        run: |
            cd /tmp
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-6.1.0.4477.zip
            unzip || sudo apt install unzip -y
            unzip sonar-scanner-6.1.0.4477.zip
            cd -

      - name: Run sonar scanner
        run: /tmp/sonar-scanner-6.1.0.4477/bin/sonar-scanner
